# Generated by Django 2.2.5 on 2019-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='fir',
            field=models.TextField(),
        ),
    ]
