# Generated by Django 2.2.5 on 2019-10-16 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191016_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 17, 59, 22, 615250)),
        ),
    ]
