# Generated by Django 2.2.5 on 2019-10-16 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20191016_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('crime', models.CharField(max_length=100)),
                ('punishment', models.CharField(max_length=100)),
                ('date_of_entry', models.DateTimeField(default=datetime.datetime(2019, 10, 16, 18, 16, 52, 517568))),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 16, 18, 16, 52, 517568)),
        ),
    ]
