# Generated by Django 2.2.5 on 2019-10-17 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20191016_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='prisoner_aadhar_no',
            field=models.IntegerField(default=100000000000, verbose_name=range(100000000000, 1000000000000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 2, 3, 275938)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 2, 3, 275938)),
        ),
    ]
