# Generated by Django 2.2.5 on 2019-10-17 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20191017_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 11, 0, 750377)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 11, 0, 750377)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='prisoner_aadhar_no',
            field=models.BigIntegerField(),
        ),
    ]
