# Generated by Django 2.2.5 on 2019-10-17 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20191017_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('visitor_aadhar_no', models.BigIntegerField()),
                ('prisoner_aadhar_no', models.BigIntegerField()),
                ('date_of_visit', models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 37, 50, 639293))),
            ],
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 37, 50, 638296)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 9, 37, 50, 639293)),
        ),
    ]
