# Generated by Django 2.2.5 on 2019-10-17 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20191017_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='guard',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('duty_hours', models.IntegerField()),
                ('guard_aadhar_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('shift', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='prisoner',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 13, 35, 956661)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 13, 35, 957659)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='prisoner_aadhar_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 13, 35, 957659)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='prisoner_aadhar_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.prisoner'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_aadhar_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
