# Generated by Django 2.2.5 on 2019-10-17 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_auto_20191017_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 15, 37, 977662)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 15, 37, 978659)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 15, 37, 978659)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='prisoner_aadhar_no',
            field=models.BigIntegerField(),
        ),
    ]
