# Generated by Django 2.2.5 on 2019-10-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20191017_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 16, 9, 546042)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 16, 9, 546042)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 16, 9, 547039)),
        ),
    ]
