# Generated by Django 2.2.5 on 2019-10-17 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20191017_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 18, 53, 46720)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 18, 53, 47718)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 18, 53, 47718)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='prisoner_aadhar_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.prisoner'),
        ),
    ]
