# Generated by Django 2.2.5 on 2019-10-17 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20191017_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvisitors',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 46, 28, 602601)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 46, 28, 601604)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 46, 28, 601604)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 17, 46, 28, 602601)),
        ),
    ]
