# Generated by Django 2.2.5 on 2019-10-17 12:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20191017_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='alloted_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.prisoner'),
        ),
        migrations.AlterField(
            model_name='allvisitors',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 15, 58, 359226)),
        ),
        migrations.AlterField(
            model_name='fir',
            name='File_Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 15, 58, 358228)),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 15, 58, 358228)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_of_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 18, 15, 58, 359226)),
        ),
    ]
